//Maya Preference 2025 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "Z:/WORKsync/00_Work/Projects/Prism/OldManFalls/03_Production/Assets/Gale/Scenefiles/CFX/CFX/Gale_CFX_v0032.ma"
 -sva "RecentFilesList" "Z:/WORKsync/00_Work/Projects/Prism/OldManFalls/03_Production/Assets/Gale/Scenefiles/CFX/CFX/Gale_CFX_v0031.ma"
 -sva "RecentFilesList" "Z:/WORKsync/00_Work/Projects/Prism/OldManFalls/03_Production/Shots/test_anim/sh_04_Fly_Emily/Scenefiles/cfx/CharacterEffects/test_anim-sh_04_Fly_Emily_CharacterEffects_v0005.ma"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 ;

