//Maya Preference 2024 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "C:/Users/unilo/Desktop/Human_Modeling_v0003.ma"
 -sva "RecentFilesList" "Z:/SHORTCUT/Lord_Of_The_Ring/03_Production/Assets/Character/Balrog/Scenefiles/Animation/Rigging/Balrog_Rigging_v0001.ma"
 -sva "RecentFilesList" "C:/Users/unilo/Desktop/Balrog_Anatomy_v0009_tmp.ma"
 -sva "RecentFilesList" "Z:/WORKsync/00_Work/Projects/Prism/Anatomy/03_Production/Assets/Character/Human/Scenefiles/Rigging/Rigging/Human_Rigging_v0003.ma"
 -sva "RecentFilesList" "Z:/Lorenzo/RedRaion/JurassicJungleRaw-Maya/Maya/scenes/Rig_dinosauri_Vecchi/Velociraptor.mb"
 -sva "RecentFilesList" "Z:/Lorenzo/RedRaion/JurassicJungleRaw-Maya/Maya/rig/03_Production/Assets/Characters/Velociraptor/Scenefiles/mod/Modeling/Velociraptor_Modeling_v0001.ma"
 -sva "RecentFilesList" "Z:/Lorenzo/RedRaion/JurassicJungleRaw-Maya/Maya/rig/03_Production/Assets/Characters/Velociraptor/Scenefiles/mod/Modeling/Velociraptor_Modeling_v0002.ma"
 -sva "RecentFilesList" "Z:/Lorenzo/RedRaion/JurassicJungleRaw-Maya/Maya/rig/03_Production/Assets/Characters/Velociraptor/Scenefiles/mod/Modeling/Velociraptor_Modeling_v0003.ma"
 -sva "RecentFilesList" "Z:/Lorenzo/RedRaion/JurassicJungleRaw-Maya/Maya/rig/03_Production/Assets/Characters/Velociraptor/Scenefiles/rig/Rigging/Velociraptor_Rigging_v0001.ma"
 -sva "RecentFilesList" "C:/Users/unilo/Desktop/Velociraptor_Rigging_v0001.ma"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "C:/projects/Ayon_Pipeline_Test/Prop/work/Icosphere"
 -sva "RecentProjectsList" "C:/Users/unilo/Desktop/test_CV"
 ;

